spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:application-aws.yml
      - classpath:application-credentials.yml
      - classpath:application-oauth.yml
      - classpath:application-jwt.yml
      - classpath:application-swagger.yml


  datasource:
    url: jdbc:h2:tcp://localhost/~/gojip
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080


