spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:application-aws.yml
      - classpath:application-credentials.yml
      - classpath:application-oauth.yml
      - classpath:application-jwt.yml
      - classpath:application-swagger.yml

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/gojip
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#      location: /users/kim65/temp-file # 업로드된 파일이 임시로 저장되는 디스크 위치


server:
  port: 8080


